kind: Service
apiVersion: v1
metadata:
  name: cassandra
spec:
  ports:
    - name: "cql"
      protocol: "TCP"
      port: 9042
      targetPort:  9042
      nodePort: 0
---
kind: Endpoints
apiVersion: v1
metadata:
  name: cassandra
  namespace: development
subsets:
  - addresses:
      - ip: 10.0.1.1
      - ip: 10.0.1.2
      - ip: 10.0.1.3
    ports:
      - name: "cql"
        port: 9042