apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hello-impl:1.0-SNAPSHOT
          # Remove for a real project, the image is picked up locally for the integration test
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /alive
              port: 8558
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8558
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          ports:
            - containerPort: 9000
              name: "http"
          env:
            # The Kubernetes API discovery will use this service name to look for
            # nodes with this value in the 'app' label.
            # This can be customized with the 'pod-label-selector' setting.
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_OPTS
              value: "-Dconfig.resource=kube-application.conf"
            - name: CASSANDRA_SERVICE_NAME
              value: "_cql._tcp.cassandra.default.svc.cluster.local"
            - name: KAFKA_SERVICE_NAME
              value: "_broker._tcp.kafka.default.svc.cluster.local"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: hello-application-secret
                  key: secret
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: hello